apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-7hjx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-7hjx
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-7hjx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-7hjx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-7hjx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zuwv-tenant/rhtap-demo-app/hacbs-test-project-7hjx@sha256:f67bac8858b3ab998755db4e44e5dbd29c7c0763091bb7a522b7834ec9233bab
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
